import React, { createContext, useContext, useState } from 'react';
import { Language } from '@/shared/types/types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  'pt-br': {
    'app.title': 'MaterialShare Pro',
    'auth.login': 'Entrar',
    'auth.register': 'Cadastrar',
    'auth.hint': 'Contas Demo: admin@demo.com, client@demo.com, distributor@demo.com, consultant@demo.com (Senha: 123456)',
    'landing.client.title': 'Bem-vindo à Área do Cliente',
    'landing.client.desc': 'Tenha acesso exclusivo a toda documentação técnica e novidades dos nossos produtos.',
    'landing.client.benefit.1': 'Download de Manuais e Certificados',
    'landing.client.benefit.2': 'Visualização de Catálogos em Alta Definição',
    'landing.client.benefit.3': 'Acesso a Vídeos de Instrução e Uso',
    'landing.distributor.title': 'Portal do Parceiro Distribuidor',
    'landing.distributor.desc': 'Acelere suas vendas com ferramentas de marketing e tabelas comerciais atualizadas.',
    'landing.distributor.benefit.1': 'Acesso a Tabelas de Preços Confidenciais',
    'landing.distributor.benefit.2': 'Download de Kits de Marketing (Posts, Banners)',
    'landing.distributor.benefit.3': 'Prioridade em Lançamentos de Produtos',
    'landing.consultant.title': 'Academia de Vendas',
    'landing.consultant.desc': 'Domine o portfólio e feche mais negócios com nossos materiais de apoio.',
    'landing.consultant.benefit.1': 'Treinamentos Técnicos e Comerciais',
    'landing.consultant.benefit.2': 'Scripts de Vendas e Argumentação',
    'landing.consultant.benefit.3': 'Materiais de Apoio para Apresentações',
    'dashboard.title': 'Materiais Disponíveis',
    'dashboard.desc': 'Explore, visualize e baixe todos os materiais disponíveis para o seu perfil.',
    'admin.title': 'Painel Administrativo',
    'admin.desc': 'Gerencie materiais, usuários e a aparência da plataforma.',
    'common.logout': 'Sair',
    'role.client': 'Cliente',
    'role.distributor': 'Distribuidor',
    'role.consultant': 'Consultor',
    'role.manager': 'Gestor',
    'role.super_admin': 'Super Admin',
    'material.type.pdf': 'Documento PDF',
    'material.type.image': 'Imagem',
    'material.type.video': 'Vídeo',
    'material.type.audio': 'Áudio',
    'material.type.html': 'Página Interativa',
    'no.materials': 'Nenhum material encontrado com os filtros atuais.',
    'no.results': 'Nenhum resultado encontrado',
    'add.material': 'Adicionar Material',
    'edit.material': 'Editar Material',
    'delete': 'Excluir',
    'edit': 'Editar',
    'view': 'Visualizar',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'title': 'Título',
    'type': 'Tipo',
    'permissions': 'Permissões',
    'actions': 'Ações',
    'status': 'Status',
    'active': 'Ativo',
    'inactive': 'Inativo',
    'manage.assets': 'Gerenciar Arquivos',
    'asset.url': 'URL do Arquivo',
    'asset.subtitle': 'URL da Legenda',
    'edit.assets.title': 'Gerenciar Versões: ',
    'empty.url.hint': 'Deixe a URL vazia para remover a versão deste idioma.',
    'url.placeholder.pdf': 'URL direta ou Link do Google Drive',
    'url.placeholder.image': 'URL direta ou Link do Google Drive',
    'url.placeholder.video': 'YouTube, Vimeo, Drive ou URL MP4 direta',
    'url.placeholder.audio': 'Link do áudio (MP3, Google Drive, etc.)',
    'url.help.text': 'Aceita links de compartilhamento do Google Drive, YouTube e Vimeo.',
    'search.placeholder': 'Buscar por nome...',
    'filter.title': 'Categorias',
    'filter.all': 'Todos os Materiais',
    'filter.pdf': 'Documentos PDF',
    'filter.image': 'Imagens',
    'filter.video': 'Vídeos',
    'filter.audio': 'Áudios',
    'filter.html': 'Interativo',
    'tab.materials': 'Materiais',
    'tab.users': 'Usuários',
    'tab.settings': 'Configurações',
    'tab.analytics': 'Métricas',
    'tab.collections': 'Trilhas',
    'user.edit': 'Editar Usuário',
    'user.filter.all': 'Todos os Perfis',
    'user.filter.status.all': 'Todos os Status',
    'user.status.pending': 'Pendente',
    'user.status.active': 'Ativo',
    'user.status.inactive': 'Inativo',
    'user.status.rejected': 'Rejeitado',
    'user.action.approve': 'Aprovar',
    'user.action.reject': 'Reprovar',
    'user.action.inactivate': 'Inativar',
    'user.action.delete': 'Excluir Usuário',
    'user.invite': 'Convites de Cadastro',
    'user.invite.copy': 'Copiar Link',
    'user.invite.copied': 'Copiado!',
    'user.access.types': 'Permissões de Tipos de Arquivo',
    'user.access.hint': 'Se nenhum for selecionado, o usuário terá acesso a todos os tipos permitidos para seu perfil.',
    'comm.title': 'Enviar Mensagem',
    'comm.send': 'Enviar',
    'comm.success': 'Mensagem enviada com sucesso para o fluxo N8N!',
    'comm.type.email': 'E-mail',
    'comm.type.whatsapp': 'WhatsApp',
    'comm.email.subject': 'Assunto',
    'comm.email.subtitle': 'Subtítulo',
    'comm.email.body': 'Corpo do E-mail',
    'comm.wa.type': 'Tipo de Mensagem',
    'comm.wa.text': 'Apenas Texto',
    'comm.wa.file': 'Texto + Arquivo',
    'comm.wa.message': 'Mensagem',
    'comm.file.url': 'URL do Arquivo/Anexo',
    'confirm.delete.title': 'Confirmar Exclusão',
    'confirm.delete.message': 'Tem certeza que deseja excluir este item? Esta ação é irreversível.',
    'confirm.delete.confirm': 'Sim, Excluir',
    'analytics.total.views': 'Total de Visualizações',
    'analytics.unique.users': 'Usuários Únicos',
    'analytics.top.material': 'Material Mais Acessado',
    'analytics.col.views': 'Visualizações',
    'analytics.col.users': 'Usuários',
    'analytics.col.last_access': 'Último Acesso',
    'analytics.detail.title': 'Histórico de Acesso',
    'analytics.detail.user': 'Usuário',
    'analytics.detail.date': 'Data/Hora',
    'analytics.detail.lang': 'Idioma',
    'analytics.empty': 'Nenhum acesso registrado ainda.',
    'analytics.rank.materials': 'Top 5 Materiais',
    'analytics.rank.users': 'Top 5 Usuários Ativos',
    'analytics.filter.type': 'Filtrar por Tipo de Documento',
    'analytics.filter.role': 'Filtrar por Perfil de Usuário',
    'analytics.overview': 'Visão Geral',
    'analytics.rankings': 'Rankings',
    'analytics.detail': 'Detalhamento',
    'analytics.filters': 'Filtros de Métricas',
    'analytics.trails.started': 'Trilhas Iniciadas',
    'analytics.trails.completed': 'Trilhas Concluídas',
    'analytics.completion.rate': 'Taxa de Conclusão',
    'analytics.trails.ranking': 'Ranking de Trilhas',
    'analytics.no.data': 'Sem dados',
    'analytics.accesses': 'acessos',
    // Dashboard
    'level': 'Nível',
    'next': 'Próximo',
    'library': 'Biblioteca',
    'pro.tip': 'Dica Pro',
    'pro.tip.search': 'para focar na busca rapidamente.',
    'pro.tip.shortcuts': 'para ver todos os atalhos.',
    'clear.filters': 'Limpar filtros',
    'versions': 'Versões',
    'untitled': 'Sem título',
    // Trails / Collections
    'trail': 'Trilha',
    'trails': 'Trilhas',
    'trails.title': 'Trilhas de Aprendizagem',
    'trails.desc': 'Complete trilhas, acumule XP e avance de nível.',
    'trail.learning': 'Trilha de Aprendizagem',
    'trail.back': 'Voltar para Trilhas',
    'trail.completed': 'Trilha concluída!',
    'trail.no.materials': 'Esta trilha ainda não tem materiais.',
    'trail.no.available': 'Nenhuma trilha disponível',
    'trail.no.available.desc': 'As trilhas de aprendizagem serão exibidas aqui.',
    'trail.xp.on.complete': 'XP ao concluir',
    'trail.view': 'Ver trilha',
    'trail.new': 'Nova Trilha',
    'trail.search': 'Buscar coleções...',
    'trail.none.created': 'Nenhuma trilha criada ainda.',
    'trail.celebration.title': 'Trilha Concluída!',
    'trail.celebration.congrats': 'Parabéns! Você completou a trilha',
    'trail.celebration.bonus': 'XP de bônus!',
    'trail.celebration.continue': 'Continuar',
    // Progress
    'progress.completed': 'Concluído',
    'progress.in.progress': 'Em andamento',
    'progress.review': 'Revisar',
    'progress.continue': 'Continuar',
    'progress.start': 'Iniciar',
    'progress.of': 'de',
    'progress.completed.items': 'concluídos',
    'progress.materials': 'materiais',
    'progress.material': 'material',
    'collection.completed': 'Concluída',
    // Settings
    'settings.options': 'Opções',
    'settings.identity': 'Identidade Visual',
    'settings.integrations': 'Integrações',
    'settings.themes': 'Temas',
    'settings.gamification': 'Gamificação',
    'settings.ranks': 'Patentes & XP',
    'settings.save': 'Salvar Alterações',
    'settings.saved': 'Configurações salvas e aplicadas!',
    'settings.app.name': 'Nome da Aplicação',
    'settings.logo.url': 'URL do Logo',
    'settings.webhook.url': 'URL do Webhook (N8N)',
    'settings.webhook.hint': 'Esta URL será chamada via POST com um payload JSON sempre que uma mensagem for enviada.',
    'settings.theme.light': '', // deprecated - dark only
    'settings.theme.dark': 'Tema Dark',
    'settings.theme.customize': 'Personalização de Temas',
    'settings.theme.base': 'Estrutura Base',
    'settings.theme.typography': 'Tipografia',
    'settings.theme.brand': 'Marca',
    'settings.theme.status': 'Status',
    'settings.theme.bg': 'Fundo geral',
    'settings.theme.surface': 'Cards e headers',
    'settings.theme.borders': 'Linhas divisórias',
    'settings.theme.titles': 'Títulos',
    'settings.theme.captions': 'Legendas',
    'settings.theme.buttons': 'Botões e destaques',
    'settings.theme.active': 'Ativo',
    'settings.theme.pending': 'Pendente',
    'settings.theme.danger': 'Perigo',
    'settings.gamification.desc': 'Defina os níveis de gamificação, nomes e pontuação mínima. Use as setas para reordenar.',
    'settings.gamification.add': 'Adicionar nova patente',
    'settings.gamification.name': 'Nome da patente',
    'settings.gamification.min.xp': 'XP mínimo',
    'settings.gamification.color': 'Cor',
    'settings.gamification.add.btn': 'Adicionar',
    'settings.gamification.none': 'Nenhuma patente configurada.',
    'settings.gamification.delete.confirm': 'Excluir a patente',
    'settings.invite.view': 'Visualizar',
    'settings.invite.copy': 'Copiar',
    'settings.invite.copied': 'Copiado!',
    // Misc
    'all': 'Todos',
    'user.none.found': 'Nenhum usuário encontrado.',
    'material.none.found': 'Nenhum material encontrado.',
    'error': 'Erro',
    'error.save.material': 'Erro ao salvar material',
    'error.delete': 'Erro ao excluir',
    'error.update.status': 'Erro ao atualizar status',
    'use': 'Use',
    'press': 'Pressione',
    'tags': 'Tags',
    'analytics.trails': 'Trilhas',
  },
  'en-us': {
    'app.title': 'MaterialShare Pro',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.hint': 'Demo Accounts: admin@demo.com, client@demo.com, distributor@demo.com, consultant@demo.com (Pass: 123456)',
    'landing.client.title': 'Welcome to Client Area',
    'landing.client.desc': 'Get exclusive access to all technical documentation and news about our products.',
    'landing.client.benefit.1': 'Download Manuals and Certificates',
    'landing.client.benefit.2': 'View High Definition Catalogs',
    'landing.client.benefit.3': 'Access Instruction and Usage Videos',
    'landing.distributor.title': 'Distributor Partner Portal',
    'landing.distributor.desc': 'Accelerate your sales with marketing tools and updated commercial tables.',
    'landing.distributor.benefit.1': 'Access Confidential Price Lists',
    'landing.distributor.benefit.2': 'Download Marketing Kits (Posts, Banners)',
    'landing.distributor.benefit.3': 'Priority on Product Launches',
    'landing.consultant.title': 'Sales Academy',
    'landing.consultant.desc': 'Master the portfolio and close more deals with our support materials.',
    'landing.consultant.benefit.1': 'Technical and Commercial Training',
    'landing.consultant.benefit.2': 'Sales Scripts and Argumentation',
    'landing.consultant.benefit.3': 'Support Materials for Presentations',
    'dashboard.title': 'Available Materials',
    'dashboard.desc': 'Explore, view and download all materials available for your profile.',
    'admin.title': 'Admin Panel',
    'admin.desc': 'Manage materials, users and the platform appearance.',
    'common.logout': 'Logout',
    'role.client': 'Client',
    'role.distributor': 'Distributor',
    'role.consultant': 'Consultant',
    'role.manager': 'Manager',
    'role.super_admin': 'Super Admin',
    'material.type.pdf': 'PDF Document',
    'material.type.image': 'Image',
    'material.type.video': 'Video',
    'material.type.audio': 'Audio',
    'material.type.html': 'Interactive Page',
    'no.materials': 'No materials found matching current filters.',
    'no.results': 'No results found',
    'add.material': 'Add Material',
    'edit.material': 'Edit Material',
    'delete': 'Delete',
    'edit': 'Edit',
    'view': 'View',
    'save': 'Save',
    'cancel': 'Cancel',
    'title': 'Title',
    'type': 'Type',
    'permissions': 'Permissions',
    'actions': 'Actions',
    'status': 'Status',
    'active': 'Active',
    'inactive': 'Inactive',
    'manage.assets': 'Manage Files',
    'asset.url': 'File URL',
    'asset.subtitle': 'Subtitle URL',
    'edit.assets.title': 'Manage Versions: ',
    'empty.url.hint': 'Leave URL empty to remove the version for this language.',
    'url.placeholder.pdf': 'Direct URL or Google Drive Link',
    'url.placeholder.image': 'Direct URL or Google Drive Link',
    'url.placeholder.video': 'YouTube, Vimeo, Drive or Direct MP4',
    'url.placeholder.audio': 'Audio link (MP3, Google Drive, etc.)',
    'url.help.text': 'Supports sharing links from Google Drive, YouTube, and Vimeo.',
    'search.placeholder': 'Search by name...',
    'filter.title': 'Categories',
    'filter.all': 'All Materials',
    'filter.pdf': 'PDF Documents',
    'filter.image': 'Images',
    'filter.video': 'Videos',
    'filter.audio': 'Audio',
    'filter.html': 'Interactive',
    'tab.materials': 'Materials',
    'tab.users': 'Users',
    'tab.settings': 'Settings',
    'tab.analytics': 'Analytics',
    'tab.collections': 'Trails',
    'user.edit': 'Edit User',
    'user.filter.all': 'All Roles',
    'user.filter.status.all': 'All Statuses',
    'user.status.pending': 'Pending',
    'user.status.active': 'Active',
    'user.status.inactive': 'Inactive',
    'user.status.rejected': 'Rejected',
    'user.action.approve': 'Approve',
    'user.action.reject': 'Reject',
    'user.action.inactivate': 'Deactivate',
    'user.action.delete': 'Delete User',
    'user.invite': 'Registration Invites',
    'user.invite.copy': 'Copy Link',
    'user.invite.copied': 'Copied!',
    'user.access.types': 'File Type Permissions',
    'user.access.hint': 'If none selected, user will have access to all types allowed for their profile.',
    'comm.title': 'Send Message',
    'comm.send': 'Send',
    'comm.success': 'Message sent successfully to N8N flow!',
    'comm.type.email': 'Email',
    'comm.type.whatsapp': 'WhatsApp',
    'comm.email.subject': 'Subject',
    'comm.email.subtitle': 'Subtitle',
    'comm.email.body': 'Email Body',
    'comm.wa.type': 'Message Type',
    'comm.wa.text': 'Text Only',
    'comm.wa.file': 'Text + File',
    'comm.wa.message': 'Message',
    'comm.file.url': 'File/Attachment URL',
    'confirm.delete.title': 'Confirm Deletion',
    'confirm.delete.message': 'Are you sure you want to delete this item? This action cannot be undone.',
    'confirm.delete.confirm': 'Yes, Delete',
    'analytics.total.views': 'Total Views',
    'analytics.unique.users': 'Unique Users',
    'analytics.top.material': 'Most Viewed Material',
    'analytics.col.views': 'Views',
    'analytics.col.users': 'Users',
    'analytics.col.last_access': 'Last Access',
    'analytics.detail.title': 'Access History',
    'analytics.detail.user': 'User',
    'analytics.detail.date': 'Date/Time',
    'analytics.detail.lang': 'Language',
    'analytics.empty': 'No access logs recorded yet.',
    'analytics.rank.materials': 'Top 5 Materials',
    'analytics.rank.users': 'Top 5 Active Users',
    'analytics.filter.type': 'Filter by Document Type',
    'analytics.filter.role': 'Filter by User Role',
    'analytics.overview': 'Overview',
    'analytics.rankings': 'Rankings',
    'analytics.detail': 'Details',
    'analytics.filters': 'Analytics Filters',
    'analytics.trails.started': 'Trails Started',
    'analytics.trails.completed': 'Trails Completed',
    'analytics.completion.rate': 'Completion Rate',
    'analytics.trails.ranking': 'Trails Ranking',
    'analytics.no.data': 'No data',
    'analytics.accesses': 'views',
    'level': 'Level',
    'next': 'Next',
    'library': 'Library',
    'pro.tip': 'Pro Tip',
    'pro.tip.search': 'to focus on search quickly.',
    'pro.tip.shortcuts': 'to see all shortcuts.',
    'clear.filters': 'Clear filters',
    'versions': 'Versions',
    'untitled': 'Untitled',
    'trail': 'Trail',
    'trails': 'Trails',
    'trails.title': 'Learning Trails',
    'trails.desc': 'Complete trails, earn XP and level up.',
    'trail.learning': 'Learning Trail',
    'trail.back': 'Back to Trails',
    'trail.completed': 'Trail completed!',
    'trail.no.materials': 'This trail has no materials yet.',
    'trail.no.available': 'No trails available',
    'trail.no.available.desc': 'Learning trails will be displayed here.',
    'trail.xp.on.complete': 'XP on completion',
    'trail.view': 'View trail',
    'trail.new': 'New Trail',
    'trail.search': 'Search collections...',
    'trail.none.created': 'No trails created yet.',
    'trail.celebration.title': 'Trail Completed!',
    'trail.celebration.congrats': 'Congratulations! You completed the trail',
    'trail.celebration.bonus': 'bonus XP!',
    'trail.celebration.continue': 'Continue',
    'progress.completed': 'Completed',
    'progress.in.progress': 'In progress',
    'progress.review': 'Review',
    'progress.continue': 'Continue',
    'progress.start': 'Start',
    'progress.of': 'of',
    'progress.completed.items': 'completed',
    'progress.materials': 'materials',
    'progress.material': 'material',
    'collection.completed': 'Completed',
    'settings.options': 'Options',
    'settings.identity': 'Brand Identity',
    'settings.integrations': 'Integrations',
    'settings.themes': 'Themes',
    'settings.gamification': 'Gamification',
    'settings.ranks': 'Ranks & XP',
    'settings.save': 'Save Changes',
    'settings.saved': 'Settings saved and applied!',
    'settings.app.name': 'Application Name',
    'settings.logo.url': 'Logo URL',
    'settings.webhook.url': 'Webhook URL (N8N)',
    'settings.webhook.hint': 'This URL will be called via POST with a JSON payload whenever a message is sent.',
    'settings.theme.light': '', // deprecated - dark only
    'settings.theme.dark': 'Dark Theme',
    'settings.theme.customize': 'Theme Customization',
    'settings.theme.base': 'Base Structure',
    'settings.theme.typography': 'Typography',
    'settings.theme.brand': 'Brand',
    'settings.theme.status': 'Status',
    'settings.theme.bg': 'General background',
    'settings.theme.surface': 'Cards and headers',
    'settings.theme.borders': 'Divider lines',
    'settings.theme.titles': 'Headings',
    'settings.theme.captions': 'Captions',
    'settings.theme.buttons': 'Buttons and accents',
    'settings.theme.active': 'Active',
    'settings.theme.pending': 'Pending',
    'settings.theme.danger': 'Danger',
    'settings.gamification.desc': 'Define gamification levels, names and minimum score. Use arrows to reorder.',
    'settings.gamification.add': 'Add new rank',
    'settings.gamification.name': 'Rank name',
    'settings.gamification.min.xp': 'Minimum XP',
    'settings.gamification.color': 'Color',
    'settings.gamification.add.btn': 'Add',
    'settings.gamification.none': 'No ranks configured.',
    'settings.gamification.delete.confirm': 'Delete rank',
    'settings.invite.view': 'View',
    'settings.invite.copy': 'Copy',
    'settings.invite.copied': 'Copied!',
    'all': 'All',
    'user.none.found': 'No users found.',
    'material.none.found': 'No materials found.',
    'error': 'Error',
    'error.save.material': 'Error saving material',
    'error.delete': 'Error deleting',
    'error.update.status': 'Error updating status',
    'use': 'Use',
    'press': 'Press',
    'tags': 'Tags',
    'analytics.trails': 'Trails',
  },
  'es-es': {
    'app.title': 'MaterialShare Pro',
    'auth.login': 'Acceso',
    'auth.register': 'Registrarse',
    'auth.hint': 'Cuentas Demo: admin@demo.com, client@demo.com, distributor@demo.com, consultant@demo.com (Clave: 123456)',
    'landing.client.title': 'Bienvenido al Área del Cliente',
    'landing.client.desc': 'Obtenga acceso exclusivo a toda la documentación técnica y novedades de nuestros productos.',
    'landing.client.benefit.1': 'Descarga de Manuales y Certificados',
    'landing.client.benefit.2': 'Visualización de Catálogos en Alta Definición',
    'landing.client.benefit.3': 'Acceso a Videos de Instrucción y Uso',
    'landing.distributor.title': 'Portal del Socio Distribuidor',
    'landing.distributor.desc': 'Acelere sus ventas con herramientas de marketing y tablas comerciales actualizadas.',
    'landing.distributor.benefit.1': 'Acceso a Listas de Precios Confidenciales',
    'landing.distributor.benefit.2': 'Descarga de Kits de Marketing (Posts, Banners)',
    'landing.distributor.benefit.3': 'Prioridad en Lanzamientos de Productos',
    'landing.consultant.title': 'Academia de Ventas',
    'landing.consultant.desc': 'Domine el portafolio y cierre más negocios con nuestros materiales de apoyo.',
    'landing.consultant.benefit.1': 'Entrenamientos Técnicos y Comerciales',
    'landing.consultant.benefit.2': 'Guiones de Ventas y Argumentación',
    'landing.consultant.benefit.3': 'Materiales de Apoyo para Presentaciones',
    'dashboard.title': 'Materiales Disponibles',
    'dashboard.desc': 'Explore, visualice y descargue todos los materiales disponibles para su perfil.',
    'admin.title': 'Panel de Administración',
    'admin.desc': 'Gestione materiales, usuarios y la apariencia de la plataforma.',
    'common.logout': 'Cerrar Sesión',
    'role.client': 'Cliente',
    'role.distributor': 'Distribuidor',
    'role.consultant': 'Consultor',
    'role.manager': 'Gestor',
    'role.super_admin': 'Súper Admin',
    'material.type.pdf': 'Documento PDF',
    'material.type.image': 'Imagen',
    'material.type.video': 'Video',
    'material.type.audio': 'Audio',
    'material.type.html': 'Página Interactiva',
    'no.materials': 'No se encontraron materiales con los filtros actuales.',
    'no.results': 'Sin resultados',
    'add.material': 'Añadir Material',
    'edit.material': 'Editar Material',
    'delete': 'Eliminar',
    'edit': 'Editar',
    'view': 'Ver',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'title': 'Título',
    'type': 'Tipo',
    'permissions': 'Permisos',
    'actions': 'Acciones',
    'status': 'Estado',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'manage.assets': 'Gestionar Archivos',
    'asset.url': 'URL del Archivo',
    'asset.subtitle': 'URL del Subtítulo',
    'edit.assets.title': 'Gestionar Versiones: ',
    'empty.url.hint': 'Deje la URL vacía para eliminar la versión de este idioma.',
    'url.placeholder.pdf': 'URL directa o Link de Google Drive',
    'url.placeholder.image': 'URL directa o Link de Google Drive',
    'url.placeholder.video': 'YouTube, Vimeo, Drive o URL MP4 directa',
    'url.placeholder.audio': 'Enlace del audio (MP3, Google Drive, etc.)',
    'url.help.text': 'Soporta enlaces de Google Drive, YouTube y Vimeo.',
    'search.placeholder': 'Buscar por nombre...',
    'filter.title': 'Categorías',
    'filter.all': 'Todos los Materiales',
    'filter.pdf': 'Documentos PDF',
    'filter.image': 'Imágenes',
    'filter.video': 'Videos',
    'filter.audio': 'Audios',
    'filter.html': 'Interactivo',
    'tab.materials': 'Materiales',
    'tab.users': 'Usuarios',
    'tab.settings': 'Configuración',
    'tab.analytics': 'Métricas',
    'tab.collections': 'Rutas',
    'user.edit': 'Editar Usuario',
    'user.filter.all': 'Todos los Perfiles',
    'user.filter.status.all': 'Todos los Estados',
    'user.status.pending': 'Pendiente',
    'user.status.active': 'Activo',
    'user.status.inactive': 'Inactivo',
    'user.status.rejected': 'Rechazado',
    'user.action.approve': 'Aprobar',
    'user.action.reject': 'Rechazar',
    'user.action.inactivate': 'Desactivar',
    'user.action.delete': 'Eliminar Usuario',
    'user.invite': 'Invitaciones de Registro',
    'user.invite.copy': 'Copiar Enlace',
    'user.invite.copied': '¡Copiado!',
    'user.access.types': 'Permisos de Tipos de Archivo',
    'user.access.hint': 'Si no selecciona ninguno, el usuario tendrá acceso a todos los tipos permitidos para su perfil.',
    'comm.title': 'Enviar Mensaje',
    'comm.send': 'Enviar',
    'comm.success': '¡Mensaje enviado con éxito al flujo N8N!',
    'comm.type.email': 'Email',
    'comm.type.whatsapp': 'WhatsApp',
    'comm.email.subject': 'Asunto',
    'comm.email.subtitle': 'Subtítulo',
    'comm.email.body': 'Cuerpo del Email',
    'comm.wa.type': 'Tipo de Mensaje',
    'comm.wa.text': 'Solo Texto',
    'comm.wa.file': 'Texto + Archivo',
    'comm.wa.message': 'Mensaje',
    'comm.file.url': 'URL del Archivo/Adjunto',
    'confirm.delete.title': 'Confirmar Eliminación',
    'confirm.delete.message': '¿Está seguro de que desea eliminar este elemento? Esta acción es irreversible.',
    'confirm.delete.confirm': 'Sí, Eliminar',
    'analytics.total.views': 'Vistas Totales',
    'analytics.unique.users': 'Usuarios Únicos',
    'analytics.top.material': 'Material Más Visto',
    'analytics.col.views': 'Vistas',
    'analytics.col.users': 'Usuarios',
    'analytics.col.last_access': 'Último Acceso',
    'analytics.detail.title': 'Historial de Acceso',
    'analytics.detail.user': 'Usuario',
    'analytics.detail.date': 'Fecha/Hora',
    'analytics.detail.lang': 'Idioma',
    'analytics.empty': 'Aún no hay registros de acceso.',
    'analytics.rank.materials': 'Top 5 Materiales',
    'analytics.rank.users': 'Top 5 Usuarios Activos',
    'analytics.filter.type': 'Filtrar por Tipo de Documento',
    'analytics.filter.role': 'Filtrar por Perfil de Usuario',
    'analytics.overview': 'Visión General',
    'analytics.rankings': 'Rankings',
    'analytics.detail': 'Detalle',
    'analytics.filters': 'Filtros de Métricas',
    'analytics.trails.started': 'Rutas Iniciadas',
    'analytics.trails.completed': 'Rutas Completadas',
    'analytics.completion.rate': 'Tasa de Finalización',
    'analytics.trails.ranking': 'Ranking de Rutas',
    'analytics.no.data': 'Sin datos',
    'analytics.accesses': 'accesos',
    'level': 'Nivel',
    'next': 'Siguiente',
    'library': 'Biblioteca',
    'pro.tip': 'Consejo Pro',
    'pro.tip.search': 'para enfocar la búsqueda rápidamente.',
    'pro.tip.shortcuts': 'para ver todos los atajos.',
    'clear.filters': 'Limpiar filtros',
    'versions': 'Versiones',
    'untitled': 'Sin título',
    'trail': 'Ruta',
    'trails': 'Rutas',
    'trails.title': 'Rutas de Aprendizaje',
    'trails.desc': 'Complete rutas, acumule XP y suba de nivel.',
    'trail.learning': 'Ruta de Aprendizaje',
    'trail.back': 'Volver a Rutas',
    'trail.completed': '¡Ruta completada!',
    'trail.no.materials': 'Esta ruta aún no tiene materiales.',
    'trail.no.available': 'No hay rutas disponibles',
    'trail.no.available.desc': 'Las rutas de aprendizaje se mostrarán aquí.',
    'trail.xp.on.complete': 'XP al completar',
    'trail.view': 'Ver ruta',
    'trail.new': 'Nueva Ruta',
    'trail.search': 'Buscar colecciones...',
    'trail.none.created': 'Aún no se han creado rutas.',
    'trail.celebration.title': '¡Ruta Completada!',
    'trail.celebration.congrats': '¡Felicidades! Completaste la ruta',
    'trail.celebration.bonus': '¡XP de bonus!',
    'trail.celebration.continue': 'Continuar',
    'progress.completed': 'Completado',
    'progress.in.progress': 'En progreso',
    'progress.review': 'Revisar',
    'progress.continue': 'Continuar',
    'progress.start': 'Iniciar',
    'progress.of': 'de',
    'progress.completed.items': 'completados',
    'progress.materials': 'materiales',
    'progress.material': 'material',
    'collection.completed': 'Completada',
    'settings.options': 'Opciones',
    'settings.identity': 'Identidad Visual',
    'settings.integrations': 'Integraciones',
    'settings.themes': 'Temas',
    'settings.gamification': 'Gamificación',
    'settings.ranks': 'Rangos & XP',
    'settings.save': 'Guardar Cambios',
    'settings.saved': '¡Configuración guardada y aplicada!',
    'settings.app.name': 'Nombre de la Aplicación',
    'settings.logo.url': 'URL del Logo',
    'settings.webhook.url': 'URL del Webhook (N8N)',
    'settings.webhook.hint': 'Esta URL será llamada via POST con un payload JSON cada vez que se envíe un mensaje.',
    'settings.theme.light': '', // deprecated - dark only
    'settings.theme.dark': 'Tema Oscuro',
    'settings.theme.customize': 'Personalización de Temas',
    'settings.theme.base': 'Estructura Base',
    'settings.theme.typography': 'Tipografía',
    'settings.theme.brand': 'Marca',
    'settings.theme.status': 'Estado',
    'settings.theme.bg': 'Fondo general',
    'settings.theme.surface': 'Cards y headers',
    'settings.theme.borders': 'Líneas divisorias',
    'settings.theme.titles': 'Títulos',
    'settings.theme.captions': 'Leyendas',
    'settings.theme.buttons': 'Botones y acentos',
    'settings.theme.active': 'Activo',
    'settings.theme.pending': 'Pendiente',
    'settings.theme.danger': 'Peligro',
    'settings.gamification.desc': 'Defina los niveles de gamificación, nombres y puntuación mínima. Use las flechas para reordenar.',
    'settings.gamification.add': 'Añadir nuevo rango',
    'settings.gamification.name': 'Nombre del rango',
    'settings.gamification.min.xp': 'XP mínimo',
    'settings.gamification.color': 'Color',
    'settings.gamification.add.btn': 'Añadir',
    'settings.gamification.none': 'No hay rangos configurados.',
    'settings.gamification.delete.confirm': 'Eliminar rango',
    'settings.invite.view': 'Ver',
    'settings.invite.copy': 'Copiar',
    'settings.invite.copied': '¡Copiado!',
    'all': 'Todos',
    'user.none.found': 'No se encontraron usuarios.',
    'material.none.found': 'No se encontraron materiales.',
    'error': 'Error',
    'error.save.material': 'Error al guardar material',
    'error.delete': 'Error al eliminar',
    'error.update.status': 'Error al actualizar estado',
    'use': 'Use',
    'press': 'Presione',
    'tags': 'Etiquetas',
    'analytics.trails': 'Rutas',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt-br');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
